config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, 
    path: 'admin', 
    path_names: { 
      sign_in: 'entrar', 
      sign_out: 'sair', 
      password: 'senha',
      registration: 'cadastro', 
      sign_up: 'cadastrar' 
    },
    controllers: {
      sessions: 'admins/sessions',
      registrations: 'admins/registrations',
      passwords: 'admins/passwords'
    }
  devise_for :users, 
    path: '/', 
    path_names: { 
      sign_in: 'entrar', 
      sign_out: 'sair', 
      password: 'senha',
      registration: 'cadastro', 
      sign_up: 'cadastrar' 
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }

  resources :books
  resources :comments, only: %i[create destroy]
  resources :book_of_users, only: %i[create destroy]
  resources :categories
  
  namespace :users do
    resources :books, only: %i[index]
  end

  root to: 'books#index'

  get '/landing', to: 'landing_page#index'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_one_attached :cover, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :book_of_users, class_name: 'BookOfUser', dependent: :destroy
  has_many :users, through: :book_of_users

  validates :title, :description, :author_name, presence: true

  def set_cover
    self.cover.attached? ? self.cover : 'bookcover.jpg'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: %i[index show]
  before_action :set_categories, only: %i[new edit]

  def index
    @books_query = Book.ransack(params[:search])
    books = @books_query.result(distinct: true)
    @categories = Category.all.select { |category| category.books.count > 0 }.map do |category|
      {
        id: category.id,
        title: category.title,
        books: books.where(category_id: category.id).limit(6).order(created_at: :desc)
      }
    end
  end

  def show; end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      redirect_to books_path, notice: 'Livro cadastrado com sucesso.'
    else
      flash.now[:alert] = @book.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @book.update book_params
      redirect_to book_path(@book), notice: 'Livro atualizado com sucesso.'
    else
      flash.now[:alert] = @book.errors.full_messages
      render :edit
    end
  end

  def destroy
    redirect_to books_path, notice: 'Livro removido com sucesso.' if @book.destroy
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :author_name, :cover, :category_id)
  end

  def set_categories
    @categories = Category.all.map { |category| [category.title, category.id] }
  end
end

app/controllers/users/books_controller.rb
class Users::BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = current_user.books
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users/books_helper.rb
module Users::BooksHelper
end

app/views/books/_book_actions.html.erb
<% if current_admin %>
  <%= link_to 'Editar', edit_book_path(@book), class: 'btn btn-sm btn-info' %>
  <%= link_to 'Remover', book_path(@book), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-sm btn-danger' %>
<% else %>
  <%= link_to 'Já li', book_of_users_path({ book_of_user: { book_id: @book.id, status: 'readed' } }), method: :post, remote: true, class: 'btn btn-sm btn-success' %>
  <%= link_to 'Quero ler', book_of_users_path({ book_of_user: { book_id: @book.id, status: 'to_read' } }), method: :post, remote: true, class: 'btn btn-sm btn-success' %>
  <%= link_to 'Quero comprar', book_of_users_path({ book_of_user: { book_id: @book.id, status: 'to_shop' } }), method: :post, remote: true, class: 'btn btn-sm btn-success' %>
<% end %>

app/views/books/_books.html.erb
<div class="row d-flex justify-content-center align-items-center mb-4">
  <div class="col-12">
    <div class="jumbotron">
      <h1 class="">BookLovers</h1>
      <p class="lead">O webapp perfeito para amantes de livros.</p>
      <hr class="my-4">
      <%= search_form_for @books_query, remote: true, class: 'inline-form' do |f| %>
        <div class="input-group">
          <div class="input-group-prepend">
            <%= sort_link(@books_query, :title, {}, { class: 'btn btn-outline-secondary', :remote => true, :method => :get } ) do %>
              <strong class="">Título</strong>
            <% end %>
          </div>
          <%= f.search_field :title_or_description_or_author_name_cont, class: 'form-control', placeholder: 'Qual livro deseja ler hoje?' %>
          <div class="input-group-append">
            <%= f.submit 'Buscar', class: "btn btn-outline-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if @categories.count > 0%>
  <% @categories.each do |category| %>
    <div class="splide">
      <h4><%= link_to category[:title], category_path(category[:id]), class: 'text-dark' %></h4>
	    <div class="splide__track">
        <div class="row splide__list">
          <% if category[:books].count > 0 %>
            <% category[:books].each do |book| %>
              <div class="splide__slide">
                <div class="card mb-3" style="max-width: 540px;">
                  <div class="row no-gutters">
                    <div class="col-md-4">
                      <%= link_to book_path(book) do %>
                        <%= image_tag book.set_cover, class: 'card-img-top' %>
                      <% end %>
                    </div>
                    <div class="col-md-8">
                      <div class="card-body">
                        <%= link_to book_path(book) do %>
                          <h5 class="text-dark card-title"><%= book.title %></h5>
                        <% end %>
                        <p class="card-text"><%= book.description.first(40) %>...</p>
                        <p class="card-text"><small class="text-muted"><%= book.author_name %></small></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/_comments.html.erb
<%= form_with url: comments_path, method: :post, remote: true, class: 'mb-5' do |f| %>
  <%= f.hidden_field :book_id, value: @book.id %>
  <%= f.label 'comment_content', 'Adicione um comentário' %>
  <%= f.rich_text_area 'comment[content]', id: 'comment_content' %>
  <%= f.submit 'Comentar', class: 'btn btn-success mt-2' %>
<% end %>
<% @book.comments&.each do |comment| %>
  <div class="row mb-3">
    <div class="col-12">
      <div class="card shadow-sm">
        <div class="card-body">
          <div class="mb-2">
          <%= image_tag((comment.member_type == 'Admin' ? 'user-avatar.png' : comment.member.set_avatar), widht: 20, height: 20) %>
            <strong><%= (comment.member_type == 'Admin' ? comment.member.email.split('@').first : comment.member.name) %></strong>
          </div>
          <%= comment.content %>
        </div>
        <% if comment.member == current_member %>
          <div class="card-footer">
            <%= link_to 'Remover comentário', comment_path({ id: comment.id, book_id: @book.id }), method: :delete, remote: true, data: { confirm: 'Tem certeza? ' }, class: 'btn btn-danger btn-sm' if comment.valid? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: @book, multipart: true, local: true, remote: false do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, placeholder: 'Ex: Game of Thrones', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Descricão' %>
    <%= f.text_area :description, placeholder: 'Descricão', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :author_name, 'Nome do Autor' %>
    <%= f.text_field :author_name, placeholder: 'Ex: Stephen King', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category_id, 'Selecione a categoria' %>
    <%= f.select :category_id, @categories, { prompt: 'Selecione a categoria' }, class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroupFileAddon01">Capa do livro</span>
      </div>
      <div class="custom-file">
        <%= f.file_field :cover, class: 'custom-file-input', id: 'inputGroupFile01' %>
        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
      </div>
    </div>    
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: 'btn btn-block btn-success shadow' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<section class="books my-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="card shadow p-4">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/books/index.html.erb
<section class="books my-5" data-controller="books">
  <div class="container">
    <div id="book-results">
      <%= render 'books' %>
    </div>
  </div>  
</section>

app/views/books/index.js.erb
document.querySelector('#book-results').innerHTML = ("<%= j render partial: 'books' %>");

app/views/books/new.html.erb
<section class="books my-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h5 class="card-title text-center">Adicionar novo livro</h5>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/books/show.html.erb
<section class="books my-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="card shadow">
          <%= image_tag @book.set_cover, class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= @book.title %></h5>
            <p class="card-text"><%= @book.description %></p>
            <p><strong><%= @book.author_name %></strong></p>
          </div>
          <div class="card-footer" id="user-book-actions">
            <%= render 'book_actions' %>
          </div>
        </div>
      </div>
      <div id="book-comments" class="col-12 col-md-8 col-lg-6 align-self-start">
        <%= render 'comments' %>
      </div>
    </div>
  </div>  
</section>