config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, 
    path: 'admin', 
    path_names: { 
      sign_in: 'entrar', 
      sign_out: 'sair', 
      password: 'senha',
      registration: 'cadastro', 
      sign_up: 'cadastrar' 
    },
    controllers: {
      sessions: 'admins/sessions',
      registrations: 'admins/registrations',
      passwords: 'admins/passwords'
    }
  devise_for :users, 
    path: '/', 
    path_names: { 
      sign_in: 'entrar', 
      sign_out: 'sair', 
      password: 'senha',
      registration: 'cadastro', 
      sign_up: 'cadastrar' 
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }

  resources :books
  resources :comments, only: %i[create destroy]
  resources :book_of_users, only: %i[create destroy]
  resources :categories
  
  namespace :users do
    resources :books, only: %i[index]
  end

  root to: 'books#index'

  get '/landing', to: 'landing_page#index'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :title, :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: %i[show]
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path, notice: 'Categoria cadastrada com sucesso.'
    else
      flash.now[:alert] = @category.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @category.update category_params
      redirect_to categories_path, notice: 'Categoria atualizada com sucesso.'
    else
      flash.now[:alert] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    redirect_to categories_path, notice: 'Categoria removida com sucesso.' if @category.destroy
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, placeholder: 'Ex: Tecnologia', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, 'Descricão' %>
    <%= f.text_area :description, placeholder: 'Descricão', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: 'btn btn-block btn-success shadow' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<section class="categories my-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h5 class="card-title text-center">Editar categoria</h5>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/categories/index.html.erb
<section class="categories">
  <div class="container my-5">
    <div class="row mb-2">
      <div class="col-12">
        <h3>Categorias</h3>
      </div>
      <div class="col-12">
        <%= link_to 'Adicionar Nova', new_category_path, class: 'btn btn-success btn-sm' %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Título</th>
                <th scope="col">Descricão</th>
                <th scope="col">Acões</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <th scope="row"><%= category.id %></th>
                  <td><%= category.title %></td>
                  <td><%= category.description.first(20)... %></td>
                  <td>
                    <%= link_to 'Visualizar', category_path(category), class: 'btn btn-primary btn-sm' %>
                    <%= link_to 'Editar', edit_category_path(category), class: 'btn btn-info btn-sm' %>
                    <%= link_to 'Remover', category_path(category), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-danger btn-sm' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/categories/new.html.erb
<section class="categories my-5">
  <div class="container">
    <div class="row d-flex justify-content-center align-items-center">
      <div class="col-12 col-md-8 col-lg-6">
        <div class="card shadow">
          <div class="card-body">
            <h5 class="card-title text-center">Adicionar nova categoria</h5>
            <%= render 'form' %>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/categories/show.html.erb
<section class="categories">
  <div class="container my-5">
    <div class="row">
      <div class="col-12">
        <h3>Livros da categoria: <strong><%= @category.title %></strong></h3>
        <p class="text-muted"><%= @category.description %></p>
      </div>
    </div>
    <div class="row">
      <% if @category.books.count > 0 %>
        <% @category.books.each do |book| %>
          <div class="col-12 col-md-6 col-lg-4 mb-2">
            <div class="card mb-3" style="max-width: 540px;">
              <div class="row no-gutters">
                <div class="col-md-4">
                  <%= link_to book_path(book) do %>
                    <%= image_tag book.set_cover, class: 'card-img-top' %>
                  <% end %>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <%= link_to book_path(book) do %>
                      <h5 class="text-dark card-title"><%= book.title %></h5>
                    <% end %>
                    <p class="card-text"><%= book.description.first(40) %>...</p>
                    <p class="card-text"><small class="text-muted"><%= book.author_name %></small></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-12">
          <h3>Nenhum livro foi encontrado :(</h3>
        </div>
      <% end %>
    </div>
  </div>
</section>